### PR TITLE
Some changes

### PR DESCRIPTION
**Pull request by davellx**
All those changes are for Android :
- Corrected a bug with boolean values between haxe <-> Java GSON
- Plugged the font, it works !
- added backgroundColor
- added placeholderColor

didn't test on IOS :(

### CODE REVIEW

**Comment by davellx** [comment]
Was it so bad ? :)

**Comment by bazzisoft** [comment]
@davellx I didn't actually close this. I replaced the "master" branch with "0.1-master" the other day to support better versioning, and GitHub decided to close the pull request automatically. I've managed to rebase it to 0.1-master now.

I don't actually use this lib in my projects as I found it too hacky in the end. So rather than testing it thoroughly and merging to the main branch I might merge it into a new branch 0.2-master-beta and see if any feedback comes in?

**Comment by davellx** [comment]
I understand, I used it once and it's indeed a little bit hacky but might prove useful.
I tought that you closed it because my code was bad or something and I wondered what I should have done, but if it's ok, thank you !

**Comment by bazzisoft** [comment]
No worries, now all merged in! Thanks for sending the pull request.

**Pull request merged**
